baseURL = "https://ianmcgonigle.github.io/dilettantedad.github.io/"
languageCode = "en-us"
title = "Dilettante Dad"
theme = "hugo-theme-fluidity"
ignoreLogs = ['warning-goldmark-raw-html']
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

